#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
""" replace CR with LF """
import sys
import fileinput

for line in fileinput.input(mode='rU'):
    if line.endswith('\r'):
        print(line)
        line.replace('\r', '\n')
        print(line)

# original 'nocr' for swapping \r with \n
# I wanted to have a way to show the \r
# sys.stdout.writelines(line.replace('\r', '\n') for line in fileinput.input(mode='rU'))
